name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/upload-artifact@v4
        with:
          name: qutmc-resources
          path: |
            assets/
            pack.mcmeta
            pack.png
          retention-days: 90
